apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "%{namespace}"
  name: "%{apiname}"
  labels:
    app: "%{apiname}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "%{apiname}"
  template:
    metadata:
      labels:
        app: "%{apiname}"
    spec:
      containers:
      - name: "%{apiname}"
        image: "bazel/%{apiname}:image"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: "%{namespace}"
  name: "%{apiname}"
spec:
  selector:
    app: "%{apiname}"
  ports:
    - port: 5000
      protocol: TCP
  clusterIP: None

