name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Cache Bazel
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push service-one image to ghcr.io
      run: bazel run --stamp --embed_label=${{ github.ref_name }} //service-one:push_image

    - name: Push authz image to ghcr.io
      run: bazel run --stamp --embed_label=${{ github.ref_name }} //authz:push_image

    - name: Push envoy image to ghcr.io
      run: bazel run --stamp --embed_label=${{ github.ref_name }} //envoy:push_image
